/*
	***** BEGIN LICENSE BLOCK *****

	Copyright © 2016 Jaret Karnuta

	This file is part of Zotero.

	Zotero is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	Zotero is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU Affero General Public License for more details.

	You should have received a copy of the GNU Affero General Public License
	along with Zotero. If not, see <http://www.gnu.org/licenses/>.

	***** END LICENSE BLOCK *****
*/

{
	"translatorID": "a55463ba-e403-415b-80d4-284d5f9b4b15",
	"label": "Clinical Key",
	"creator": "Jaret M. Karnuta",
	"target": "(.*?)clinicalkey(.*?)/#\\!/(.*?)/book",
	"minVersion": "3.0",
	"maxVersion": "",
	"priority": 100,
	"inRepository": false,
	"translatorType": 4,
	"browserSupport": "gcs",
	"lastUpdated": "2016-12-24 22:48:11"
}

/*
This translator is designed specifically for use on book section portions of
ClinicalKey. It will not work on journal articles and book overview pages.
*/

function detectWeb(doc, url) {
	var contentType = doc.getElementsByClassName("content-type")[0];
	if(!contentType){
		return;
	}

	contentType = contentType.innerHTML;
	if (contentType == "Book Chapter"){
		return "bookSection";
	}
}

function doWeb(doc, url){
	var contentType = detectWeb(doc, url);

	if(!(contentType=='book' || contentType == 'bookSection')){
		return;
	}
	var newItem = new Zotero.Item(contentType);
	newItem = loadCommonAttributes(newItem, doc);

	if (contentType == 'bookSection'){
		newItem = scrapeBookSection(doc, newItem);
	}

	newItem.complete();
}

function scrapeBookSection(doc, item){
	//book title
	var bookTitle = getElementsByAttr(doc, 'data-once-text','XocsCtrl.title')[0].innerHTML;
	item.bookTitle = bookTitle;

	//section title
	var title  = getElementsByAttr(doc, 'ng-bind-html','ContentCtrl.title')[0].innerHTML;
	item.title = title;

	//authors
	var authorsList  = getElementsByAttr(doc, 'ng-bind-html','XocsCtrl.authorsHtml')[0].getElementsByTagName("a");
	for (var i = 0;i<authorsList.length;i++){
			var author = authorsList[i].innerHTML;
			if(author.includes("<")){
				author = author.split("<")[0];
			}
			item.creators.push(Zotero.Utilities.cleanAuthor(author, 'author'));
	}

	//page metadata
	var chapterAndPages = doc.getElementsByClassName("source ng-binding")[0].innerHTML.split("</a>,")[1].trim();
	var chapter = chapterAndPages.split(",")[0].trim();
	item.notes.push({"Chapter":chapter});
	item.pages = chapterAndPages.split(",")[1].trim();

	//ISBN metadata
	var isbn = getElementsByAttr(doc, "data-metadata-isbn", "")[0].getAttribute('data-metadata-isbn');
	item.isbn = isbn;

	//edition metadata
	var edition = getElementsByAttr(doc, 'data-once-text','XocsCtrl.edition')[0].innerHTML.split("Edition")[0].trim();
	item.edition = edition;

	//publisher metadata
	var datePub = getElementsByAttr(doc, 'data-once-text','XocsCtrl.copyright')[0].innerHTML;
	var date = datePub.replace(/\D/g, '');
	var pub;
	if (datePub.includes("imprint")){
		var imprint = datePub.split("by")[1].split(", an")[0].trim();
		var parent = datePub.split("imprint of")[1].split("Inc.")[0].trim();
		pub = parent+"/"+imprint;
	}
	else{
		pub = datePub.split("by")[1].split(", Inc")[0].trim();
	}
	item.date = date;
	item.publisher = pub;
	if(pub.includes("Elsevier")){
		item.place = "Philadelphia, PA";
	}

	return item;
}

/**
 * Return list of elements that have attr containing content
 */
function getElementsByAttr(doc, attr, content){
	var matching = [];
	var allElements = doc.getElementsByTagName("*");
	for (var i =0; i<allElements.length;i++){
		if(allElements[i].hasAttribute(attr)){
			if(allElements[i].getAttribute(attr).includes(content)){
				matching.push(allElements[i]);
			}
		}
	}
	return matching;
}

/**
 * Loads common attributes (same across book and book section) to the Zotero.Item loaded in doWeb
 */
function loadCommonAttributes(zoteroItem, doc){
	zoteroItem.url = doc.location.href;
	zoteroItem.notes = [{"CreatedBy":'Generated by Zotero Translator for ClinicalKey by JaretK'}];
	return zoteroItem;
}
